### ISSUE TITLE
Paper 'Relation Network for Multi-label Aerial Image Classification' Source Code

### ISSUE THREAD

**Issue by ShoupingShan** [Hua-YS/AID-Multilabel-Dataset#1]
Hi,
  I have read your wonderful work in 'Relation Network for Multi-label Aerial Image Classification', and which inspired me. It would be appreciated if you can provide me with your works' source code link or files. My Email is shp395210@outlook.com.
                                                                                                      Yours,
                                                                                                Shouping Shan

**Comment by Jiawei0o0** [comment]
Hi,
Did you get the source code? Can you share the code with me? My Email is sujiavooo@163.com. Thanks a lot!

**Comment by ShoupingShan** [comment]
Sorry, I haven't got the source code either!

**Comment by Hua-YS** [comment]
Hi @VoooWei and @ShoupingShan, sorry that I did not check the GitHub issues so often. I have published the code in another work, and the link is here https://github.com/Hua-YS/Multi-Scene-Recognition/blob/main/utils/relationnet.py
